# Generated by Django 5.0.6 on 2024-05-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinaryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photos', models.ManyToManyField(to='cloudinaryapp.photo')),
            ],
        ),
    ]
